version: 2.1.{build}
image: Visual Studio 2022
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

before_build:
- which msbuild.exe

build_script:
- ps: .\Build.ps1

test: off 

nuget:
  disable_publish_on_pr: true
build:
  publish_nuget: true
  verbosity: normal

#deploy:
#- provider: NuGet
#  name: production
#  api_key:
#    secure: ZhyqJwNBnwKrh2iknXgtLlSVWPhf8byfUdr1U8obUgxCr380nNJ8GHACRYwPP9kx
#  skip_symbols: false
#  on:
#    branch: master
#    appveyor_repo_tag: true
