version: '{build}'

pull_requests:
  do_not_increment_build_number: true

image: 'Visual Studio 2022'
configuration: Release

environment:
  TINIFY_KEY:
    secure: ZF/29NnonLrQuvAfRbhotwBPdrvQ+D+ayXVxWji8HaLYKSV2WH5kTDJSGSfB4j7S

before_build:
- which msbuild.exe

build_script:
- ps: .\Build.ps1

test: off

nuget:
  disable_publish_on_pr: true

artifacts:
- path: src\Tinify\artifacts\*.nupkg
  name: NuGet

deploy:
- provider: NuGet
  name: production
  api_key:
    secure: ZhyqJwNBnwKrh2iknXgtLlSVWPhf8byfUdr1U8obUgxCr380nNJ8GHACRYwPP9kx
  skip_symbols: false
  on:
    branch: master
    appveyor_repo_tag: true
